### ISSUE TITLE
Failed to compile when using unejected create-react-app

### ISSUE THREAD

**Issue by ckienast** [detrohutt/react-app-rewire-inline-import-graphql-ast#3]
Hi,

tried out your package today and sadly it didn't run out of the box.
I followed your readme, but still get a compile error when starting my app with react-rewired.
Seems like your babel plugin uses ES6 syntax and node can't handle that.

Any workarounds on that?
Thanks.

```./src/index.js
Module build failed: /Users/chrisnix/Coding/Node/slack-clone/client/node_modules/babel-plugin-inline-import-graphql-ast/build/index.js:1
(function (exports, require, module, __filename, __dirname) { import path, { dirname } from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at Array.map (<anonymous>)```

**Comment by detrohutt** [comment]
Ok, I've updated the first package (the dependency). That may be enough to get it working for you. You can go ahead and remove the package and reinstall it and see if that works. In the meantime, I'll update the dependency version in this package and republish to npm. Let me know if you get it working.

**Comment by detrohutt** [comment]
This package is updated as well. You can either reinstall it completely or change the dependency in your `package.json` to `react-app-rewire-inline-import-graphql-ast: "^1.0.2"`

**Comment by ckienast** [comment]
Nice one! I'll give it a try tomorrow. It's already late here in germany; like 3:30am. Thanks for that awesomely fast fix! 👍

**Comment by ckienast** [comment]
Works perfectly fine! Thanks

**Comment by detrohutt** [comment]
Awesome, enjoy!

**Comment by detrohutt** [comment]
Hey, just a heads up, you may want to check out the [new section](https://github.com/detrohutt/react-app-rewire-inline-import-graphql-ast#known-issues) I just added at the top of the README. It could save you a lot of time and frustration. Thanks for trying my package!
