### ISSUE TITLE
Problem with mutation

### ISSUE THREAD

**Issue by carosello-hub** [detrohutt/react-app-rewire-inline-import-graphql-ast#4]
Hello,
Thanks for this project :)
I wondering if I'm doing something wrong...
I'm trying to load the query below that works in all the Graphql GUI Editors and also in JS but when I use the external file I'm getting this error:
<img width="1013" alt="screen shot 2018-04-24 at 21 53 46" src="https://user-images.githubusercontent.com/38560778/39213669-17b2c03e-480a-11e8-9f73-0bcf1c8909f7.png">
Am I doing something wrong?  😄
Thank you so much.

```javascript
mutation VisitorJwt($visitorJwt: VisitorJwt) {
    VisitorJwt(visitorJwt: $visitorJwt) {
        id
        token
    }
}
```

Code where I'm loading the query:

```javascript
import JWT_QUERY from '../../data/queries/jwt/jwt.graphql';
[...]
graphql(gql(JWT_QUERY), {name: 'postMutation'})(ComponentWithMutation);
```

**Comment by detrohutt** [comment]
Hi @carosello-hub thanks for trying my plugin! The plugin runs your `.graphql` file through `gql` automatically, so there's no need to wrap it in a `gql` yourself.

So this should work:
```javascript
graphql(JWT_QUERY, {name: 'postMutation'})(ComponentWithMutation);
```

**Comment by carosello-hub** [comment]
ooops :)
sorry about that, I'm approaching to GraphQl, a lots of new things to learn :)
Thank you so much for your help!!
