### ISSUE TITLE
Watch on `.graphql` files doesn't working on Windows?

### ISSUE THREAD

**Issue by johnunclesam** [detrohutt/react-app-rewire-inline-import-graphql-ast#5]
Watch on `.graphql` files doesn't working on Windows?

**Comment by detrohutt** [comment]
That is a known issue with any babel plugins dealing with custom file extensions and not specific to this package. Unfortunately there's not anything I can do about it. You can find more info [in this issue from another babel plugin](https://github.com/kentcdodds/babel-plugin-preval/issues/19).
